// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnyw2SbrpoLy9TXCqE6ucaLbPxCX-wKSE',
    appId: '1:852094620721:web:fd8c06fc16246242717110',
    messagingSenderId: '852094620721',
    projectId: 'myapp-5d2cf',
    authDomain: 'myapp-5d2cf.firebaseapp.com',
    storageBucket: 'myapp-5d2cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ1jMwoDpT45Go6eDsLLujz6rC-CE0e4w',
    appId: '1:852094620721:android:13e9b2cb1e437d9d717110',
    messagingSenderId: '852094620721',
    projectId: 'myapp-5d2cf',
    storageBucket: 'myapp-5d2cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK5Ziz7AC28PwvWhmzrIi4AzyfD9hokl0',
    appId: '1:852094620721:ios:702c5b217a13450f717110',
    messagingSenderId: '852094620721',
    projectId: 'myapp-5d2cf',
    storageBucket: 'myapp-5d2cf.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK5Ziz7AC28PwvWhmzrIi4AzyfD9hokl0',
    appId: '1:852094620721:ios:702c5b217a13450f717110',
    messagingSenderId: '852094620721',
    projectId: 'myapp-5d2cf',
    storageBucket: 'myapp-5d2cf.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnyw2SbrpoLy9TXCqE6ucaLbPxCX-wKSE',
    appId: '1:852094620721:web:f1be2e712a99b8c9717110',
    messagingSenderId: '852094620721',
    projectId: 'myapp-5d2cf',
    authDomain: 'myapp-5d2cf.firebaseapp.com',
    storageBucket: 'myapp-5d2cf.appspot.com',
  );
}
